language: java
jdk:
  - oraclejdk8  
script:
  - mvn -f ./hotelbuddy/pom.xml compile && mvn -f ./hotelbuddy/pom.xml test
  - mvn -f ./hotelbuddyGui/pom.xml compile && mvn -f ./hotelbuddyGui/pom.xml test